POST https://localhost:7070/storechains
Content-Type: application/json

{
    "Name": "Miky",
    "Image": "miky.png"
} 

###

GET https://localhost:7070/StoreChains/65a51733-3a56-450d-8025-e0383b28b0ed