POST https://localhost:5001/storechains
Content-Type: application/json

{
    "Name": "Miky",
    "Image": "miky.png"
} 

###
# Should result in error due to short name:
POST https://localhost:5001/storechains
Content-Type: application/json

{
    "Name": "M",
    "Image": "miky.png"
} 

###
GET https://localhost:5001/StoreChains/65a51733-3a56-450d-8025-e0383b28b0ed