version: '3.4'

services:
  priskollenserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      # - "8080"
      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - test_priskollenserver_network
  
  mariadb:
    ports:
      - "5002:3306/tcp"
    networks:
      - test_priskollenserver_network
    environment:
      - TZ=Europe/Stockholm
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=priskollen_db
      - MYSQL_USER=priskollen
      - MYSQL_PASSWORD=123456

networks:
  test_priskollenserver_network:
    name: test_priskollenserver_network