@hostAddress = https://localhost:5001
@controller = storechains
@fullAddress = {{hostAddress}}/{{controller}}

### GET STORECHAIN BY ID
GET {{fullAddress}}/2
Content-Type: application/json

### GET ALL STORECHAINS

GET {{fullAddress}}
Content-Type: application/json

### GET STORECHAIN
GET https://localhost:5001/StoreChains/6

### CREATE STORECHAINS
POST {{fullAddress}}
Content-Type: application/json

{
    "Name": "Miky",
    "Image": "miky.png"
} 

### CREATE STORECHAINS
# Should result in error due to short name:
POST {{fullAddress}}
Content-Type: application/json

{
    "Name": "M",
    "Image": "miky.png"
} 

### UPDATE STORECHAIN BY ID
PUT {{fullAddress}}/1
Content-Type: application/json

{
    "Name": "Mikael Gustafsson",
    "Image": "miky2.png"
}