@hostAddress = https://localhost:5001
@controller = stores
@fullAddress = {{hostAddress}}/{{controller}}

### GET ALL STORES
GET {{fullAddress}}
Content-Type: application/json

### GET STORE BY ID
GET {{fullAddress}}/3
Content-Type: application/json